FROM mcr.microsoft.com/devcontainers/dotnet:0-6.0-bullseye
RUN curl -sL https://tools.circleci.foc.zone/install-certs | bash -
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/Quicken_Loans_Root_CA.crt